version: "3"

services:

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper_crypto
    ports:
      - 2181:2181
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    restart: unless-stopped
      
  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka_crypto
    ports:
      - 9092:9092
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
    depends_on:
      - zookeeper
    volumes:
      - kafka-data:/var/lib/kafka/data/
    restart: unless-stopped
    
  kafka-producer:
    image: python:3.9-slim
    user: root
    container_name: kafka_producer_crypto
    command: > 
         sh -c "pip install kafka-python==2.0.2 requests==2.28.1
         && /usr/local/bin/python3 /app/scripts/producerData.py"
    volumes:
      - ~/Projects/Python/financial-data/:/app
    depends_on:
      - kafka
    networks:
      - crypto-network

  streamlit:
      image: python:3.9-slim
      user: root
      container_name: streamlit
      command: > 
          sh -c "pip install -r /app/requirements.txt
          && streamlit run /app/scripts/dataVizualization.py"
      volumes:
        - ~/Projects/Python/financial-data/:/app
      ports:
        - 8501:8501
      networks:
        - crypto-network

  kafdrop:
     image: obsidiandynamics/kafdrop:latest
     container_name: kafdrop_crypto
     environment:
       KAFKA_BROKERCONNECT: kafka:9092
     ports:
       - 9001:9000
     depends_on:
      - kafka
     restart: unless-stopped

  spark:
    image: docker.io/bitnami/spark:3.3.1
    environment:
      - SPARK_MODE=master
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
    ports:
      - '8585:8080'
    volumes:
      - ~/Projects/Python/financial-data/:/app
  spark-worker:
    image: docker.io/bitnami/spark:3.3.1
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark:7077
      - SPARK_WORKER_MEMORY=1G
      - SPARK_WORKER_CORES=1
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no

networks:
  crypto-network:
    driver: bridge
volumes:
  kafka-data:
    driver: local