version: "3"

services:

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper-crypto
    ports:
      - 2181:2181
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    restart: unless-stopped
  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka-crypto
    ports:
      - 9092:9092
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper-crypto:2181
      KAFKA_ADVERTISED_HOST_NAME: kafka:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT_HOST://localhost:9092,PLAINTEXT://kafka:29092
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    depends_on:
      - zookeeper
    volumes:
      - kafka-data-crypto:/var/lib/kafka/data/
    restart: unless-stopped
  streamlit:
      image: streamlit
      build:
        context: ./docker/
        dockerfile: Dockerfile
      container_name: streamlit-crypto
      ports:
        - 8501:8501
      networks:
        - crypto-network

# OPTIONAL
  kafdrop:
     image: obsidiandynamics/kafdrop:latest
     container_name: kafdrop-crypto
     environment:
       KAFKA_BROKERCONNECT: kafka:29092
     ports:
       - 9001:9000
     depends_on:
      - zookeeper
      - kafka
     restart: unless-stopped

  spark:
    image: docker.io/bitnami/spark:3.3.1
    container_name: spark-crypto
    environment:
      - SPARK_MODE=master
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
    ports:
      - '8585:8080'
    volumes:
      - ../:/app
  spark-worker:
    image: docker.io/bitnami/spark:3.3.1
    container_name: spark-worker-crypto
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark:7077
      - SPARK_WORKER_MEMORY=1G
      - SPARK_WORKER_CORES=1
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no

networks:
  crypto-network:
    driver: bridge
volumes:
  kafka-data-crypto:
    driver: local